# Generated by Django 5.2.17 on 2026-08-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riot_id', models.CharField(max_length=40, unique=True)),
                ('english', models.CharField(max_length=80)),
                ('traditional', models.CharField(max_length=80)),
                ('pinyin', models.CharField(max_length=120)),
                ('cn_name', models.CharField(max_length=80)),
                ('cn_title', models.CharField(max_length=80)),
                ('lanes', models.CharField(max_length=80)),
                ('icon', models.URLField()),
            ],
            options={
                'ordering': ['english'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('traditional', models.CharField(max_length=32)),
                ('pinyin', models.CharField(max_length=64)),
                ('english', models.CharField(max_length=160)),
                ('when', models.TextField()),
                ('tags', models.CharField(help_text='comma-separated', max_length=160)),
                ('roles', models.CharField(blank=True, max_length=80)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
